# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # xcodebuild(
    #   {
    #     clean: true,
    #     build: true,
    #     output_name: "EditableForm.ipa",
    #     scheme: "EditableForm",
    #     sdk: "iphonesimulator16.2",
    #     destination: "platform=iOS Simulator,name=iPhone 14 Pro",
    #     xcargs: "ONLY_ACTIVE_ARCH=NO"
    #   }
    # )

    gym(
      scheme: "EditableForm" ,
      configuration: "Debug",
      clean: true,
      export_method: "development",
      output_directory: "~/Desktop",
      output_name: "EditableForm.ipa",
      xcargs: "ARCHIVE=YES"
    )

    sh("open -a Simulator")
    sh("xcrun simctl install booted ~/Desktop/EditableForm.ipa")
  end
end
